### ISSUE TITLE
Fixing the read me, and mentioning way to contribute.

### ISSUE THREAD

**Issue by harshnagarkar** [erikhom/aida#2]
A set of instruction that need to be followed to contribute, do we need to create a branch when we want to contribute. Is there any example of using AIDA with images.

**Comment by erikhom** [comment]
Creating a branch makes sense -- the main should only represent the official current version.  I would welcome a set of instructions for how to contribute, if you could help write that ;).  There used to be AIDA test images bundled with releases...if that has changed, I can dig that out and we can post with code...it's supposed to be there!
