### ISSUE TITLE
How to run AIDA by commandline?

### ISSUE THREAD

**Issue by harshnagarkar** [erikhom/aida#7]
Hey if I wanted to run AIDA by command line, how can I do that? @jalong2

**Comment by jalong2** [comment]
Take a look in AIDA.py and you’ll see all the command tags for each setting. I never ran it that way, but nothing I changed should’ve affected it. It works by overwriting the settings file, so you should only need to use the tags for settings you want different from the file.

**Comment by harshnagarkar** [comment]
Oh okay alright, I look into it.
